import { PatientForm } from "../interfaces/patient-form";

export const PATIENT_FORM_LABELS = {
  // ==== title ====
  TITLE_INFO: "ข้อมูลส่วนตัว",
  TITLE_EMERGENCY: "ข้อมูลผู้ติดต่อฉุกเฉิน",

  // ==== ข้อมูลส่วนตัว ====
  FNAME: {
    LABEL: "ชื่อ",
    NAME: "firstName",
    PLACEHOLDER: "ชื่อจริง",
    VALIDATE_MESSAGE: "กรุณากรอกชื่อ",
    TYPE: "text",
    OPTION: null,
  },
  MNAME: {
    LABEL: "ชื่อกลาง",
    NAME: "middleName",
    PLACEHOLDER: "ชื่อกลาง (ถ้ามี)",
    VALIDATE_MESSAGE: "",
    TYPE: "text",
    OPTION: null,
  },
  LNAME: {
    LABEL: "นามสกุล",
    NAME: "lastName",
    PLACEHOLDER: "นามสกุล",
    VALIDATE_MESSAGE: "กรุณากรอกนามสกุล",
    TYPE: "text",
    OPTION: null,
  },
  DATE_OF_BIRTH: {
    LABEL: "วันเดือนปีเกิด",
    NAME: "dateOfBirth",
    PLACEHOLDER: "วว/ดด/ปปปป",
    VALIDATE_MESSAGE: "กรุณากรอกวันเดือนปีเกิด",
    TYPE: "datePicker",
    OPTION: null,
  },
  GENDER: {
    LABEL: "เพศ",
    NAME: "gender",
    PLACEHOLDER: "เพศ",
    VALIDATE_MESSAGE: "กรุณากรอกเพศ",
    TYPE: "select",
    OPTION: [
      { value: "male", label: "ชาย" },
      { value: "female", label: "หญิง" },
      { value: "other", label: "อื่น ๆ" },
    ],
  },
  PHONE: {
    LABEL: "เบอร์โทรศัพท์",
    NAME: "phone",
    PLACEHOLDER: "เบอร์โทรศัพท์",
    VALIDATE_MESSAGE: "กรุณากรอกเบอร์โทรศัพท์",
    TYPE: "text",
    OPTION: null,
  },
  EMAIL: {
    LABEL: "อีเมล์",
    NAME: "email",
    PLACEHOLDER: "อีเมล์",
    VALIDATE_MESSAGE: "กรุณากรอกอีเมล์",
    TYPE: "text",
    OPTION: null,
  },
  ADDRESS: {
    LABEL: "ที่อยู่",
    NAME: "address",
    PLACEHOLDER: "ที่อยู่",
    VALIDATE_MESSAGE: "กรุณากรอกที่อยู่",
    TYPE: "text",
    OPTION: null,
  },
  PREFERRED_LANGUAGE: {
    LABEL: "ภาษาที่ใช้สื่อสาร",
    NAME: "preferredLanguage",
    PLACEHOLDER: "ภาษาที่ใช้สื่อสาร",
    VALIDATE_MESSAGE: "กรุณากรอกภาษาที่ใช้สื่อสาร",
    TYPE: "select",
    OPTION: [
      { value: "th", label: "ไทย" },
      { value: "en", label: "English" },
      { value: "cn", label: "中文 (Chinese)" },
      { value: "jp", label: "日本語 (Japanese)" },
      { value: "kr", label: "한국어 (Korean)" },
      { value: "mm", label: "မြန်မာ (Myanmar)" },
      { value: "kh", label: "ខ្មែរ (Khmer)" },
      { value: "vn", label: "Tiếng Việt (Vietnamese)" },
      { value: "other", label: "อื่น ๆ" },
    ] as const,
  },
  NATIONALITY: {
    LABEL: "สัญชาติ",
    NAME: "nationality",
    PLACEHOLDER: "สัญชาติ",
    VALIDATE_MESSAGE: "กรุณากรอกสัญชาติ",
    TYPE: "select",
    OPTION: [
      { value: "thai", label: "ไทย" },
      { value: "american", label: "American" },
      { value: "british", label: "British" },
      { value: "chinese", label: "Chinese" },
      { value: "japanese", label: "Japanese" },
      { value: "korean", label: "Korean" },
      { value: "myanmar", label: "Myanmar" },
      { value: "cambodian", label: "Cambodian" },
      { value: "laos", label: "Laotian" },
      { value: "vietnamese", label: "Vietnamese" },
      { value: "indian", label: "Indian" },
      { value: "other", label: "อื่น ๆ" },
    ] as const,
  },
  RELIGION: {
    LABEL: "ศาสนา",
    NAME: "religion",
    PLACEHOLDER: "ศาสนา",
    VALIDATE_MESSAGE: "",
    TYPE: "select",
    OPTION: [
      { value: "buddhism", label: "พุทธ" },
      { value: "christianity", label: "คริสต์" },
      { value: "islam", label: "อิสลาม" },
      { value: "hinduism", label: "ฮินดู" },
      { value: "sikhism", label: "ซิกข์" },
      { value: "judaism", label: "ยิว" },
      { value: "none", label: "ไม่มีศาสนา" },
      { value: "other", label: "อื่น ๆ" },
    ] as const,
  },

  // ==== ผู้ติดต่อฉุกเฉิน ====
  EMERGENCY_FNAME: {
    LABEL: "ชื่อผู้ติดต่อฉุกเฉิน",
    NAME: "emergencyFirstName",
    PLACEHOLDER: "ชื่อผู้ติดต่อฉุกเฉิน",
    VALIDATE_MESSAGE: "",
    TYPE: "text",
    OPTION: null,
  },
  EMERGENCY_MNAME: {
    LABEL: "ชื่อกลาง",
    NAME: "emergencyMiddleName",
    PLACEHOLDER: "ชื่อกลางผู้ติดต่อฉุกเฉิน",
    VALIDATE_MESSAGE: "",
    TYPE: "text",
    OPTION: null,
  },
  EMERGENCY_LNAME: {
    LABEL: "นามสกุล",
    NAME: "emergencyLastName",
    PLACEHOLDER: "นามสกุลผู้ติดต่อฉุกเฉิน",
    VALIDATE_MESSAGE: "",
    TYPE: "text",
    OPTION: null,
  },
  EMERGENCY_RELATION: {
    LABEL: "ความสัมพันธ์",
    NAME: "emergencyRelation",
    PLACEHOLDER: "ความสัมพันธ์",
    VALIDATE_MESSAGE: "",
    TYPE: "select",
    OPTION: [
      { value: "father", label: "บิดา" },
      { value: "mother", label: "มารดา" },
      { value: "spouse", label: "คู่สมรส" },
      { value: "son", label: "บุตรชาย" },
      { value: "daughter", label: "บุตรสาว" },
      { value: "sibling", label: "พี่น้อง" },
      { value: "relative", label: "ญาติ" },
      { value: "friend", label: "เพื่อน" },
      { value: "guardian", label: "ผู้ปกครอง" },
      { value: "other", label: "อื่น ๆ" },
    ] as const,
  },
} as const;

export const PATIENT_FORM_DEFAULT: PatientForm = {
  firstName: "",
  middleName: "",
  lastName: "",
  dateOfBirth: "",
  gender: "",
  phone: "",
  email: "",
  address: "",
  preferredLanguage: "",
  nationality: "",
  religion: "",
  emergencyFirstName: "",
  emergencyMiddleName: "",
  emergencyLastName: "",
  emergencyRelation: "",
};
